name: leon
favicon: null
layout_spectrum: 0.8340783948078752
typography_spectrum: 0.5277320889290422
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.11518551036715508
  lightness: 0.7205048021860421
  saturation: 0.7325265521649271
  rhythmicContrast: 0.41532710124738514
purpose: []
